---
alphabet: [inspect, inspected, arrived_at, radiation_level, mission_complete, mission_abort, mission_start, move]
common_alphabet: [inspect, inspected, arrived_at, radiation_level, move]
#  mission_complete, mission_abort, mission_start
main_process: "ROVER_SYSTEM"
model: "rover_model.csp" 
trace_file: "trace-json-fail-message-order.txt"
name: "rover_model4_test"
mode: "strict"
