---
alphabet: [inspect, inspected, arrived_at, radiation_level, mission_complete, mission_abort, mission_start, move]
common_alphabet: [inspect, inspected, arrived_at, radiation_level, move, mission_complete, mission_abort, mission_start]
#  
main_process: "RCSystem"
model: "robochart-version/comparison.csp" 
#trace_file: "trace-json-good.txt" # Wont work withouth mission_start
trace_file: "../inspection-rover-taros/log.json"
name: "rover_robochart_model_ras_pass"
mode: "permissive"
