---
alphabet: [inspect, inspected, arrived_at, radiation_level,  mission_abort, mission_complete, move] #mission_start
common_alphabet: [inspect, inspected, arrived_at, radiation_level, move,  mission_abort, mission_complete]
main_process: "normal(ROVER_SYSTEM)"
model: "rover_model.csp" 
trace_file: "trace-json-pass.txt"
name: "rover_model_ras_pass_normal"
mode: "strict"
